dist: trusty

os:
- linux

sudo: required

services:
  - docker

language: go

go:
  - 1.8

matrix:
  allow_failures:
  - go: tip

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/go-playground/overalls
  - go get -u github.com/mattn/goveralls

install:
  - make deps

script:
  - make test
  - make lint

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" 'quay.io';
    make build.push;
    fi