dist: trusty

os:
- linux

sudo: required

services:
  - docker

language: go

go:
- 1.8
- tip

matrix:
  allow_failures:
  - go: tip

before_install:
  - go get -u github.com/golang/dep/cmd/dep

install:
  - make deps

script:
  - make test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" 'quay.io';
    make build.push;
    fi